#!/bin/bash

repository_name="${1}"
repository_path="${3}"

[[ ${repository_name} == "gentoo" ]] || exit 0

source /lib/gentoo/functions.sh

GLSADIR="${repository_path}"/metadata/glsa
ebegin "Updating GLSAs @ $GLSADIR"
if [[ -e ${GLSADIR} ]] && [[ -e ${GLSADIR}/.git ]]; then
	git -C "${GLSADIR}" pull -q --ff-only
elif [[ ! -e ${GLSADIR} ]]; then
	git clone -q https://anongit.gentoo.org/git/data/glsa.git "${GLSADIR}"
else # [[ -e ${GLSADIR} ]]
	rsync -qa rsync://rsync.gentoo.org/gentoo-repo/metadata/glsa/ "${GLSADIR}"
fi
eend "$?"
