#!/bin/bash

repository_name="${1}"
repository_path="${3}"

[[ ${repository_name} == "gentoo" ]] || exit 0

source /lib/gentoo/functions.sh

NEWSDIR="${repository_path}"/metadata/news
ebegin "Updating news items @ ${NEWSDIR}"
if [[ -e ${NEWSDIR} ]] && [[ -e ${NEWSDIR}/.git ]]; then
	git -C "${NEWSDIR}" pull -q --ff-only
elif [[ ! -e ${NEWSDIR} ]]; then
	git clone -q https://anongit.gentoo.org/git/data/gentoo-news.git "${NEWSDIR}"
else # [[ -e ${NEWSDIR} ]]
	rsync -qa rsync://rsync.gentoo.org/gentoo-repo/metadata/news/ "${NEWSDIR}"
fi
eend $? "Try to remove ${NEWSDIR}"
