#!/bin/bash

repository_name="${1}"
repository_path="${3}"

[[ ${repository_name} == "gentoo" ]] || exit 0

source /lib/gentoo/functions.sh

DTDDIR="${repository_path}"/metadata/dtd
ebegin "Updating DTDs @ ${DTDDIR}"
if [[ -e ${DTDDIR} ]] && [[ -e ${DTDDIR}/.git ]]; then
	git -C "${DTDDIR}" pull -q --ff-only
elif [[ ! -e ${DTDDIR} ]]; then
	git clone -q https://anongit.gentoo.org/git/data/dtd.git "${DTDDIR}"
else # [[ -e ${DTDDIR} ]]
	rsync -qa rsync://rsync.gentoo.org/gentoo-repo/metadata/dtd/ "${DTDDIR}"
fi
eend "$?"
